version: "3.8"

services:
  web:
    build:
      context: .
    container_name: pizza_auth_service
    ports:
      - "8001:8001"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: pizza
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: pizza_auth
    ports:
      - "5432:5432"
